[[redirects]]
  from = "https://fancade-club.netlify.app/*"
  to = "https://ditto.cade.party/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://cade.club/*"
  to = "https://ditto.cade.party/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.cade.club/*"
  to = "https://ditto.cade.party/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://fancade.club/*"
  to = "https://ditto.cade.party/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.fancade.club/*"
  to = "https://ditto.cade.party/:splat"
  status = 301
  force = true
